package com.addressbook.repository;

import org.springframework.boot.CommandLineRunner;
import org.springframework.context.annotation.Bean;
import org.springframework.stereotype.Component;
import jakarta.persistence.EntityManager;
import jakarta.persistence.PersistenceContext;
import java.util.List;
import com.addressbook.model.Contact;

@Component
public class DatabaseInitializer implements CommandLineRunner {

    @PersistenceContext
    private EntityManager entityManager;

    public static final List<Contact> SAMPLE_CONTACTS = List.of(
        new Contact()
            .setFirstName("John")
            .setLastName("Smith")
            .setEmail("john.smith@example.com")
            .setPhoneNumber("+1-555-0123")
            .setAddress("123 Main St, Springfield")
            .setCategory("Family"),
        
        new Contact()
            .setFirstName("Sarah")
            .setLastName("Johnson")
            .setEmail("sarah.johnson@example.com")
            .setPhoneNumber("+1-555-0456")
            .setAddress("456 Oak Ave, Portland")
            .setCategory("Work"),
        
        new Contact()
            .setFirstName("Michael")
            .setLastName("Williams")
            .setEmail("michael.williams@example.com")
            .setPhoneNumber("+1-555-0789")
            .setAddress("789 Pine Rd, Seattle")
            .setCategory("Friends"),
        
        new Contact()
            .setFirstName("Emily")
            .setLastName("Brown")
            .setEmail("emily.brown@example.com")
            .setPhoneNumber("+1-555-0321")
            .setAddress("321 Elm Blvd, Austin")
            .setCategory("Family"),
        
        new Contact()
            .setFirstName("David")
            .setLastName("Davis")
            .setEmail("david.davis@example.com")
            .setPhoneNumber("+1-555-0654")
            .setAddress("654 Maple Dr, Denver")
            .setCategory("Colleagues")
    );

    @Override
    public void run(String... args) throws Exception {
        // Ensure schema is created before inserting data
        entityManager.createNativeQuery("CREATE TABLE IF NOT EXISTS contact (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, first_name VARCHAR(50), last_name VARCHAR(50), email VARCHAR(100), phone_number VARCHAR(20), address VARCHAR(255), category VARCHAR(50))").executeUpdate();
        
        // Insert sample contacts if table exists and has no records
        Long existingCount = entityManager.createQuery("SELECT COUNT(*) FROM Contact")
            .getSingleResult();
            
        if (existingCount == 0) {
            for (Contact contact : SAMPLE_CONTACTS) {
                entityManager.persist(contact);
            }
            System.out.println("Sample data initialized successfully!");
        } else {
            System.out.println("Database already contains " + existingCount + " contacts. Skipping initialization.");
        }
    }

    @Bean
    public CommandLineRunner initializeDatabase(EntityManager em) {
        return args -> {
            // Schema creation via Hibernate ddl-auto handles table structure first
            // Then we insert sample data after tables are created
            Long count = em.createQuery("SELECT COUNT(*) FROM Contact")
                          .getSingleResult();
            
            if (count == 0) {
                for (Contact contact : SAMPLE_CONTACTS) {
                    em.persist(contact);
                }
                System.out.println("Sample data initialized successfully!");
            } else {
                System.out.println("Database already contains " + count + " contacts. Skipping initialization.");
            }
        };
    }
}

src/main/resources/data.sql
